---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

#- name: Import role to install java
#  ansible.builtin.import_role:
#    name: java_install_role

- name: Install JAVA
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present

- name: Add Jenkins GPG key
  ansible.builtin.apt_key:
    url: "{{ GPG_key }}"
    state: present

- name: Add Jenkins repository to sources list
  ansible.builtin.copy:
    content: "{{ jenkins_repo }}"
    dest: /etc/apt/sources.list.d/jenkins.list

- name: Update apt cache
  ansible.builtin.apt:
   update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Ensure Jenkins service is running and enabled
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes

